# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSyncSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='软件名称')),
                ('parent_folder', models.CharField(choices=[('autoPay', '自动提款'), ('collect', '采集器'), ('cs_office', '客服办公工具'), ('acc_office', '财务办公工具'), ('it_office', '技术办公工具')], default='autoPay', max_length=50)),
                ('sub_folder', models.CharField(max_length=50)),
                ('version_num', models.CharField(max_length=5)),
                ('host', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('ssh_host_key_fingerprint', models.CharField(max_length=100)),
                ('shortcut_filename', models.CharField(max_length=50)),
                ('program_filename', models.CharField(max_length=50)),
            ],
        ),
    ]
