# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdeploy', '0003_auto_20170506_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsyncsetting',
            name='file_mask',
            field=models.CharField(default='', max_length=50, verbose_name='文件同步掩码'),
        ),
    ]
