# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdeploy', '0007_auto_20170509_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('category_folder_name', models.CharField(max_length=50, verbose_name='文件夹名')),
            ],
        ),
        migrations.CreateModel(
            name='SyncServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='服务器名')),
                ('host', models.CharField(max_length=20, verbose_name='同步源主机')),
                ('username', models.CharField(max_length=50, verbose_name='同步账户')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('ssh_host_key_fingerprint', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientsyncsetting',
            name='host',
        ),
        migrations.RemoveField(
            model_name='clientsyncsetting',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='clientsyncsetting',
            name='password',
        ),
        migrations.RemoveField(
            model_name='clientsyncsetting',
            name='ssh_host_key_fingerprint',
        ),
        migrations.RemoveField(
            model_name='clientsyncsetting',
            name='username',
        ),
        migrations.AddField(
            model_name='clientcategory',
            name='sync_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientdeploy.SyncServer'),
        ),
        migrations.AddField(
            model_name='clientsyncsetting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientdeploy.ClientCategory'),
        ),
    ]
