# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdeploy', '0009_auto_20170510_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsyncsetting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientdeploy.ClientCategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='clientsyncsetting',
            name='sync_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientdeploy.SyncServer', verbose_name='同步源服务器'),
        ),
    ]
