# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asserts',
            name='assert_code',
            field=models.CharField(default='null', max_length=50, verbose_name='资产编码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asserts',
            name='assert_status',
            field=models.CharField(choices=[('in using', '使用中'), ('idle', '闲置'), ('broken', '损坏待修')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='asserts',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='asserts',
            name='owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='使用人'),
        ),
    ]
