# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0002_auto_20170513_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asserts',
            name='assert_status',
            field=models.CharField(choices=[('in using', '使用中'), ('idle', '闲置'), ('broken', '损坏待修')], default='idle', max_length=20, verbose_name='状态'),
        ),
    ]
