# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0003_auto_20170513_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asserts',
            new_name='Assert',
        ),
    ]
