# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0004_auto_20170513_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssertChangeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='资产变更')),
                ('change_content', models.TextField(verbose_name='变更内容')),
            ],
        ),
        migrations.CreateModel(
            name='AssertChangeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='变更创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='变更修改时间')),
                ('assert_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_record_set', to='asserts.Assert', verbose_name='变更记录')),
                ('change_record_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assert_set', to='asserts.AssertChangeRecord', verbose_name='关联的资产')),
            ],
        ),
        migrations.AddField(
            model_name='assertchangerecord',
            name='related_assert',
            field=models.ManyToManyField(related_name='change_records', through='asserts.AssertChangeRelation', to='asserts.Assert'),
        ),
    ]
