# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0005_auto_20170515_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assertchangerelation',
            name='assert_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_record_set', to='asserts.Assert', verbose_name='关联的资产'),
        ),
        migrations.AlterField(
            model_name='assertchangerelation',
            name='change_record_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assert_set', to='asserts.AssertChangeRecord', verbose_name='变更记录'),
        ),
    ]
