# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asserts', '0010_auto_20170522_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assert',
            name='assert_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='资产编码'),
        ),
    ]
